"""empty message

Revision ID: a7dad34cc3a9
Revises: 
Create Date: 2018-01-31 16:12:52.853454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dad34cc3a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story', sa.Text(length=10000), nullable=True),
    sa.Column('title', sa.String(length=164), nullable=True),
    sa.Column('likenum', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=164), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story'),
    sa.UniqueConstraint('title')
    )
    op.create_table('storycs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyc', sa.Text(length=10000), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['storys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storycs')
    op.drop_table('storys')
    # ### end Alembic commands ###
